myApp.config(['$routeProvider',function($routeProvider){
  $routeProvider
  .when('/signUp',{
    templateUrl:'../views/signUpPage.html',
    controller:"signUpCtrl"
  })
  .when('/admin/dashboard',{
    templateUrl:'../views/adminDashboard.html',
    controller:'adminDashboardCtrl'
  })
  .when('/login',{
    templateUrl:'../views/login.html',
    controller:'loginCtrl'
  })
  .when('/dashboard',{
    templateUrl:'../views/dashboard.html',
    controller:'dashboardCtrl'
  })
  .when('/test/:id',{
    templateUrl:'../views/test.html',
    controller:'testCtrl'
  })

  .when('/adminTest/:id',{
    templateUrl:'../views/adminTest.html',
    controller:'adminTestCtrl'
  })
  .when('/updateTest/:id',{
    templateUrl:'../views/updateTest.html',
    controller:'updateTestCtrl'
  })
  .when('/deleteTest/:id',{
    templateUrl:'../views/delete.html',
    controller:'deleteTestCtrl'
  })
}])
console.log('wdwed');
